// AUTO-GENERATED by scripts/generate-tools-registry.mjs.
// Do not edit by hand. Run `node scripts/generate-tools-registry.mjs` to refresh.
// Hand-curated overrides (interactive componentKey, descriptions) live in tools-registry.ts.

export type ToolEntry = {
  slug: string;
  pdfName: string;
  title: string;
  moduleSlug: string;
};

export const RAW_TOOLS: ToolEntry[] = [
  {
    "slug": "tool-00a",
    "pdfName": "Tool_00A_Quick_Start_7Day_Checklist",
    "title": "Quick Start 7-Day Checklist",
    "moduleSlug": "module-00"
  },
  {
    "slug": "tool-00b",
    "pdfName": "Tool_00B_Family_Sharing_Letter",
    "title": "Family Sharing Letter",
    "moduleSlug": "module-00"
  },
  {
    "slug": "tool-01a",
    "pdfName": "Tool_01A_Starting_Point_Quick_Assessment",
    "title": "Starting Point Quick Assessment",
    "moduleSlug": "module-01"
  },
  {
    "slug": "tool-01b",
    "pdfName": "Tool_01B_Timeline_Reality_Check",
    "title": "Timeline Reality Check",
    "moduleSlug": "module-01"
  },
  {
    "slug": "tool-01c",
    "pdfName": "Tool_01C_Transition_Stage_Readiness_Assessment",
    "title": "Transition Stage Readiness Assessment",
    "moduleSlug": "module-01"
  },
  {
    "slug": "tool-02a",
    "pdfName": "Tool_02A_5_Pile_Sorting_System",
    "title": "5-Pile Sorting System",
    "moduleSlug": "module-02"
  },
  {
    "slug": "tool-02b",
    "pdfName": "Tool_02B_Two_Bag_Daily_Tidy_Tracker",
    "title": "Two-Bag Daily Tidy Tracker",
    "moduleSlug": "module-02"
  },
  {
    "slug": "tool-02c",
    "pdfName": "Tool_02C_Confidence_Building_Areas",
    "title": "Confidence Building Areas",
    "moduleSlug": "module-02"
  },
  {
    "slug": "tool-03a",
    "pdfName": "Tool_03A_Paperwork_3_Folder_System",
    "title": "Paperwork 3-Folder System",
    "moduleSlug": "module-03"
  },
  {
    "slug": "tool-03b",
    "pdfName": "Tool_03B_Sorting_Progress_Tracker",
    "title": "Sorting Progress Tracker",
    "moduleSlug": "module-03"
  },
  {
    "slug": "tool-03c",
    "pdfName": "Tool_03C_Room_By_Room_Sorting_Plan",
    "title": "Room by Room Sorting Plan",
    "moduleSlug": "module-03"
  },
  {
    "slug": "tool-04a",
    "pdfName": "Tool_04A_Sentimental_Items_3_Path",
    "title": "Sentimental Items 3-Path",
    "moduleSlug": "module-04"
  },
  {
    "slug": "tool-04b",
    "pdfName": "Tool_04B_Pick_Your_Favorites_First",
    "title": "Pick Your Favorites First",
    "moduleSlug": "module-04"
  },
  {
    "slug": "tool-04c",
    "pdfName": "Tool_04C_Move_Forward_Decision_Guide",
    "title": "Move Forward Decision Guide",
    "moduleSlug": "module-04"
  },
  {
    "slug": "tool-04d",
    "pdfName": "Tool_04D_New_Home_Space_Planner",
    "title": "New Home Space Planner",
    "moduleSlug": "module-04"
  },
  {
    "slug": "tool-05a",
    "pdfName": "Tool_05A_Smart_Prep_Budget",
    "title": "Smart Prep Budget",
    "moduleSlug": "module-05"
  },
  {
    "slug": "tool-05b",
    "pdfName": "Tool_05B_Safety_Walkthrough",
    "title": "Safety Walkthrough",
    "moduleSlug": "module-05"
  },
  {
    "slug": "tool-05c",
    "pdfName": "Tool_05C_Contractor_Bid_Comparison",
    "title": "Contractor Bid Comparison",
    "moduleSlug": "module-05"
  },
  {
    "slug": "tool-05d",
    "pdfName": "Tool_05D_Repair_Priority_Assessment",
    "title": "Repair Priority Assessment",
    "moduleSlug": "module-05"
  },
  {
    "slug": "tool-06a",
    "pdfName": "Tool_06A_Essential_Legal_Documents",
    "title": "Essential Legal Documents",
    "moduleSlug": "module-06"
  },
  {
    "slug": "tool-06b",
    "pdfName": "Tool_06B_Financial_Exploitation_Prevention",
    "title": "Financial Exploitation Prevention",
    "moduleSlug": "module-06"
  },
  {
    "slug": "tool-06c",
    "pdfName": "Tool_06C_Medicare_Medicaid_Assessment",
    "title": "Medicare Medicaid Assessment",
    "moduleSlug": "module-06"
  },
  {
    "slug": "tool-06d",
    "pdfName": "Tool_06D_Transition_Cost_Estimator",
    "title": "Transition Cost Estimator",
    "moduleSlug": "module-06"
  },
  {
    "slug": "tool-07a",
    "pdfName": "Tool_07A_Monthly_Cost_Comparison",
    "title": "Monthly Cost Comparison",
    "moduleSlug": "module-07"
  },
  {
    "slug": "tool-07b",
    "pdfName": "Tool_07B_Tour_Questions",
    "title": "Tour Questions",
    "moduleSlug": "module-07"
  },
  {
    "slug": "tool-07c",
    "pdfName": "Tool_07C_Red_Flags",
    "title": "Red Flags",
    "moduleSlug": "module-07"
  },
  {
    "slug": "tool-07d",
    "pdfName": "Tool_07D_Comparison_Scorecard",
    "title": "Comparison Scorecard",
    "moduleSlug": "module-07"
  },
  {
    "slug": "tool-08a",
    "pdfName": "Tool_08A_Estate_Documents",
    "title": "Estate Documents",
    "moduleSlug": "module-08"
  },
  {
    "slug": "tool-08b",
    "pdfName": "Tool_08B_Digital_Asset_Inventory",
    "title": "Digital Asset Inventory",
    "moduleSlug": "module-08"
  },
  {
    "slug": "tool-08c",
    "pdfName": "Tool_08C_Asset_Inventory",
    "title": "Asset Inventory",
    "moduleSlug": "module-08"
  },
  {
    "slug": "tool-08d",
    "pdfName": "Tool_08D_Decision_Makers",
    "title": "Decision Makers",
    "moduleSlug": "module-08"
  },
  {
    "slug": "tool-09a",
    "pdfName": "Tool_09A_Net_Proceeds",
    "title": "Net Proceeds",
    "moduleSlug": "module-09"
  },
  {
    "slug": "tool-09b",
    "pdfName": "Tool_09B_Cash_Offer_Checklist",
    "title": "Cash offer Checklist",
    "moduleSlug": "module-09"
  },
  {
    "slug": "tool-09c",
    "pdfName": "Tool_09C_Traditional_Listing",
    "title": "Traditional Listing",
    "moduleSlug": "module-09"
  },
  {
    "slug": "tool-09d",
    "pdfName": "Tool_09D_Decision_Pyramid",
    "title": "Decision Pyramid",
    "moduleSlug": "module-09"
  },
  {
    "slug": "tool-10a",
    "pdfName": "Tool_10A_Move_Timeline",
    "title": "Move Timeline",
    "moduleSlug": "module-10"
  },
  {
    "slug": "tool-10b",
    "pdfName": "Tool_10B_Address_Change",
    "title": "Address Change",
    "moduleSlug": "module-10"
  },
  {
    "slug": "tool-10c",
    "pdfName": "Tool_10C_Essentials_Box",
    "title": "Essentials Box",
    "moduleSlug": "module-10"
  },
  {
    "slug": "tool-10d",
    "pdfName": "Tool_10D_Utility_Transfer",
    "title": "Utility Transfer",
    "moduleSlug": "module-10"
  },
  {
    "slug": "tool-11a",
    "pdfName": "Tool_11A_Closing_Day",
    "title": "Closing Day",
    "moduleSlug": "module-11"
  },
  {
    "slug": "tool-11b",
    "pdfName": "Tool_11B_Final_Walkthrough",
    "title": "Final Walkthrough",
    "moduleSlug": "module-11"
  },
  {
    "slug": "tool-11c",
    "pdfName": "Tool_11C_Post_Closing",
    "title": "Post Closing",
    "moduleSlug": "module-11"
  },
  {
    "slug": "tool-12a",
    "pdfName": "Tool_12A_First_72_Hours",
    "title": "First 72 Hours",
    "moduleSlug": "module-12"
  },
  {
    "slug": "tool-12b",
    "pdfName": "Tool_12B_Warning_Signs",
    "title": "Warning Signs",
    "moduleSlug": "module-12"
  },
  {
    "slug": "tool-12c",
    "pdfName": "Tool_12C_Check_In_Template",
    "title": "Check-In Template",
    "moduleSlug": "module-12"
  },
  {
    "slug": "tool-12d",
    "pdfName": "Tool_12D_Routine_Builder",
    "title": "Routine Builder",
    "moduleSlug": "module-12"
  },
  {
    "slug": "tool-13a",
    "pdfName": "Tool_13A_Family_Meeting",
    "title": "Family Meeting",
    "moduleSlug": "module-13"
  },
  {
    "slug": "tool-13b",
    "pdfName": "Tool_13B_De_Escalation",
    "title": "De-Escalation",
    "moduleSlug": "module-13"
  },
  {
    "slug": "tool-13c",
    "pdfName": "Tool_13C_Task_Division",
    "title": "Task Division",
    "moduleSlug": "module-13"
  },
  {
    "slug": "tool-13d",
    "pdfName": "Tool_13D_Caregiver_Burnout",
    "title": "Caregiver Burnout",
    "moduleSlug": "module-13"
  },
  {
    "slug": "tool-14a",
    "pdfName": "Tool_14A_Aging_Cost_Calculator",
    "title": "Aging Cost Calculator",
    "moduleSlug": "module-14"
  },
  {
    "slug": "tool-14b",
    "pdfName": "Tool_14B_Home_Modification",
    "title": "Home Modification",
    "moduleSlug": "module-14"
  },
  {
    "slug": "tool-14c",
    "pdfName": "Tool_14C_Plan_B",
    "title": "Plan B",
    "moduleSlug": "module-14"
  },
  {
    "slug": "tool-15a",
    "pdfName": "Tool_15A_LTC_Decision",
    "title": "LTC Decision",
    "moduleSlug": "module-15"
  },
  {
    "slug": "tool-15b",
    "pdfName": "Tool_15B_Policy_Comparison",
    "title": "Policy Comparison",
    "moduleSlug": "module-15"
  },
  {
    "slug": "tool-15c",
    "pdfName": "Tool_15C_Affordability",
    "title": "Affordability",
    "moduleSlug": "module-15"
  },
  {
    "slug": "tool-16a",
    "pdfName": "Tool_16A_Medicare_Gap",
    "title": "Medicare Gap",
    "moduleSlug": "module-16"
  },
  {
    "slug": "tool-16b",
    "pdfName": "Tool_16B_VA_Eligibility",
    "title": "VA Eligibility",
    "moduleSlug": "module-16"
  },
  {
    "slug": "tool-16c",
    "pdfName": "Tool_16C_Medicaid_Spend_Down",
    "title": "Medicaid Spend-Down",
    "moduleSlug": "module-16"
  },
  {
    "slug": "tool-16d",
    "pdfName": "Tool_16D_Benefits_Coordination",
    "title": "Benefits Coordination",
    "moduleSlug": "module-16"
  },
  {
    "slug": "tool-17a",
    "pdfName": "Tool_17A_Trust_Selection",
    "title": "Trust Selection",
    "moduleSlug": "module-17"
  },
  {
    "slug": "tool-17b",
    "pdfName": "Tool_17B_Estate_Tax",
    "title": "Estate Tax",
    "moduleSlug": "module-17"
  },
  {
    "slug": "tool-17c",
    "pdfName": "Tool_17C_Beneficiary_Audit",
    "title": "Beneficiary Audit",
    "moduleSlug": "module-17"
  },
  {
    "slug": "tool-18a",
    "pdfName": "Tool_18A_Burnout_Assessment",
    "title": "Burnout Assessment",
    "moduleSlug": "module-18"
  },
  {
    "slug": "tool-18b",
    "pdfName": "Tool_18B_Respite_Planning",
    "title": "Respite Planning",
    "moduleSlug": "module-18"
  },
  {
    "slug": "tool-18c",
    "pdfName": "Tool_18C_Caregiver_Info",
    "title": "Caregiver Info",
    "moduleSlug": "module-18"
  },
  {
    "slug": "tool-19a",
    "pdfName": "Tool_19A_Completion_Assessment",
    "title": "Completion Assessment",
    "moduleSlug": "module-19"
  },
  {
    "slug": "tool-19a-premium-session-prep",
    "pdfName": "Tool_19A_Premium_Session_Prep",
    "title": "Premium Session Prep",
    "moduleSlug": "module-19-premium"
  },
  {
    "slug": "tool-19b-premium-intake-form",
    "pdfName": "Tool_19B_Premium_Intake_Form",
    "title": "Premium Intake Form",
    "moduleSlug": "module-19-premium"
  }
];
